# 01 - Index ticker lists (S&P 500, Nasdaq-100)

Builds the static ticker lists in `data/ticker_lists/` that Steps 3 to 5 of the README use as a
`--watch` / `--tickers` argument.

> **These lists are today's index membership, so they are survivorship biased.**
> Applying them to history keeps only the companies that survived *and* stayed in the index.
> Over half of the 2003-2007 market by dollar volume is missing from them; notebook 05 measures
> what that does to a backtest. For research, build the point-in-time universe instead
> (`scripts/build_pit_universe.py`, README Step 2 Option C). These lists are fine for a quick
> demonstration lake, which is what they are used for here.

The command-line equivalent is `python scripts/build_index_universes.py --outdir data/ticker_lists`.

## 1. Fetching

Two things about the sources changed since this notebook was first written and both had to be
fixed:

* **Wikipedia now returns HTTP 403** to urllib's default user agent, so requests must identify
  themselves. `pandas.read_html` also no longer accepts a raw HTML string, hence the `StringIO`.
* **The S&P 500 list is no longer on datahub.io** at the old URL (HTTP 404), and the Nasdaq-100
  article no longer contains a constituents table at all, so selecting "table number 4" cannot
  work. The code below searches for a table by *column name* and falls back to the committed
  list when the scrape is unavailable.

In [1]:
import io
import json
import urllib.error
import urllib.request
from pathlib import Path

import pandas as pd

REPO = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUT_DIR = REPO / "data" / "ticker_lists"          # where the pipeline actually reads its lists
USER_AGENT = "polygonio-ingestion-pipeline/1.0 (ticker list builder)"

def fetch_tables(url: str) -> list[pd.DataFrame]:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as r:
        return pd.read_html(io.StringIO(r.read().decode("utf-8", errors="replace")))

def tickers_from(tables: list[pd.DataFrame], candidates=("Symbol", "Ticker", "Ticker symbol")) -> list[str]:
    """First table carrying a ticker-like column -> sorted unique symbols, in Polygon's spelling.

    Polygon writes share classes with a dot (`BRK.B`, `BF.B`) and so does Wikipedia, so symbols pass
    through unchanged. Rewriting the dot to a dash produces tickers that match nothing in the lake.
    """
    for tbl in tables:
        for c in candidates:
            if c in tbl.columns:
                s = tbl[c].astype(str).str.strip().str.upper().str.split().str[0]
                return sorted(s[s.str.len() > 0].unique())
    raise ValueError("no ticker-like column in any table on the page")

In [2]:
sp500_symbols = tickers_from(fetch_tables("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"),
                             candidates=("Symbol", "Ticker"))
print(f"S&P 500: {len(sp500_symbols)} tickers, e.g. {sp500_symbols[:6]}")
print("share classes kept in Polygon form:", [t for t in sp500_symbols if "." in t])

S&P 500: 503 tickers, e.g. ['A', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL']
share classes kept in Polygon form: ['BF.B', 'BRK.B']

In [3]:
try:
    nasdaq100_symbols = tickers_from(fetch_tables("https://en.wikipedia.org/wiki/Nasdaq-100"),
                                     candidates=("Ticker", "Ticker symbol", "Symbol"))
    ndx_source = "wikipedia"
except (ValueError, urllib.error.URLError, urllib.error.HTTPError) as e:
    saved = OUT_DIR / "nasdaq100.json"
    nasdaq100_symbols = sorted(json.loads(saved.read_text()))
    ndx_source = f"saved list ({saved.name})"
    print(f"[WARN] Nasdaq-100 scrape unavailable ({type(e).__name__}: {e}); reused the saved list")
print(f"Nasdaq-100: {len(nasdaq100_symbols)} tickers from {ndx_source}, e.g. {nasdaq100_symbols[:6]}")

[WARN] Nasdaq-100 scrape unavailable (ValueError: no ticker-like column in any table on the page); reused the saved list
Nasdaq-100: 101 tickers from saved list (nasdaq100.json), e.g. ['AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK']

## 2. Saving

The committed lists in `data/ticker_lists/` are the ones the existing lakes were built from, so
this notebook writes a **refreshed copy alongside them** rather than overwriting them. Point the
pipeline at the refreshed files, or copy them over deliberately, once you are ready to rebuild.

In [4]:
REFRESH_DIR = OUT_DIR / "refreshed"

def save_tickers(tickers, name: str, out_dir: Path = REFRESH_DIR) -> None:
    """Save a ticker collection as TXT (one per line), CSV and JSON."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)         # parents=True: the folder may not exist yet
    ordered = sorted(set(tickers))
    (out / f"{name}.txt").write_text("\n".join(ordered))
    pd.Series(ordered).to_csv(out / f"{name}.csv", index=False, header=False)
    (out / f"{name}.json").write_text(json.dumps(ordered))
    print(f"saved {len(ordered):,} tickers -> {out.relative_to(REPO)}/{name}.{{txt,csv,json}}")

save_tickers(sp500_symbols, "sp500")
save_tickers(nasdaq100_symbols, "nasdaq100")
save_tickers(set(sp500_symbols) | set(nasdaq100_symbols), "spx_ndx_combined")

saved 503 tickers -> data/ticker_lists/refreshed/sp500.{txt,csv,json}
saved 101 tickers -> data/ticker_lists/refreshed/nasdaq100.{txt,csv,json}
saved 516 tickers -> data/ticker_lists/refreshed/spx_ndx_combined.{txt,csv,json}

In [5]:
combined = sorted(set(sp500_symbols) | set(nasdaq100_symbols))
pd.Series({"S&P 500": len(sp500_symbols), "Nasdaq-100": len(nasdaq100_symbols),
           "in both": len(set(sp500_symbols) & set(nasdaq100_symbols)),
           "combined": len(combined)}).to_frame("tickers")

            tickers
S&P 500         503
Nasdaq-100      101
in both          88
combined        516

## 3. A year of drift, which is survivorship bias in miniature

Comparing the freshly scraped list against the committed one shows how much index membership
moves in a single year. Every name in the "left the index" column is one a present-day list
would hide from a backtest, even though it traded the whole time.

In [6]:
committed = json.loads((OUT_DIR / "spx_ndx_combined.json").read_text())
entered, left = sorted(set(combined) - set(committed)), sorted(set(committed) - set(combined))
print(f"committed list: {len(committed)} tickers | refreshed list: {len(combined)} tickers")
print(f"entered since the committed list was built: {len(entered)}")
print(f"left: {len(left)}")
pd.DataFrame({"entered the index": pd.Series(entered), "left the index": pd.Series(left)}).fillna("")

committed list: 517 tickers | refreshed list: 516 tickers
entered since the committed list was built: 26
left: 27

   entered the index left the index
0               ARES            AVB
1                BNY             BK
2               CASY            CAG
3               CIEN            CPB
4               COHR           CTRA
5                CRH            CZR
6               CVNA            DAY
7               ECHO            EMN
8                EME           ENPH
9               FDXF           EPAM
10              FERG            EQR
11              FISV             FI
12               FIX           HOLX
13              FLEX            IPG
14              HONA              K
15              HOOD            KMX
16              IBKR            LKQ
17              LITE             LW
18              MRSH            MHK
19              PSKY           MKTX
20                 Q            MMC
21              RDDT            MOH
22              SNDK           MTCH
23              VEEV           PARA
24              VMRK           PAYC
25               VRT           POOL
26                              WBA

The new arrivals include fresh spin-offs (`FDXF` FedEx Freight, `HONA` Honeywell Aerospace,
`Q` Qnity Electronics) and pure ticker renames (`BNY` for BNY Mellon, `MRSH` for Marsh McLennan,
`PSKY` for Paramount Skydance). A rename is the subtle one: the company never left, but a list
keyed on today's symbol loses its entire history under the old ticker. The adjusted lakes handle
this properly through the `id` column, which follows the *company* across renames.

## 3. Do these symbols exist in the lake?

A list is only useful if its spelling matches the flat files. This is the check that catches a
dot-versus-dash mistake immediately, and it is worth running whenever the list is rebuilt.

In [7]:
import os

LAKE = Path(os.environ.get("POLYGON_LAKE_ROOT", Path.home() / "local" / "parquet_lake"))
market_day = LAKE / "day" / "all"
if market_day.is_dir():
    import pyarrow.parquet as pq
    recent = sorted(p for p in (market_day / str(pd.Timestamp.today().year - 1)).glob("*.parquet"))
    present = set()
    for f in recent:
        present |= set(pq.read_table(f, columns=["ticker"]).column("ticker").to_pylist())
    missing = [t for t in combined if t not in present]
    print(f"checked {len(combined)} tickers against {len(recent)} month files of the market day lake")
    print(f"not found: {len(missing)}" + (f" -> {missing[:15]}" if missing else "  (all present)"))
else:
    print(f"no market day lake at {market_day}; skip (set POLYGON_LAKE_ROOT or build it first)")

checked 516 tickers against 8 month files of the market day lake
not found: 7 -> ['ECHO', 'FDXF', 'FISV', 'HONA', 'MRSH', 'Q', 'VMRK']

Any symbol reported here is either freshly added to the index (no history yet), or spelled in a
way Polygon does not use. Both are worth resolving before building a lake from the list.